# Generated by Django 2.0.2 on 2018-06-11 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('changeable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('capabilities', models.ManyToManyField(to='backend.Capability')),
            ],
        ),
        migrations.CreateModel(
            name='ESRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actioncap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actioncap', to='backend.Capability')),
                ('actiondev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actiondev', to='backend.Device')),
                ('triggercapE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggercapE', to='backend.Capability')),
                ('triggercapS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggercapS', to='backend.Capability')),
                ('triggerdevE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggerdevE', to='backend.Device')),
                ('triggerdevS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggerdevS', to='backend.Device')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('active', models.BooleanField()),
                ('cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Capability')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
        migrations.AddField(
            model_name='capability',
            name='channel',
            field=models.ManyToManyField(to='backend.Channel'),
        ),
    ]
