# Generated by Django 2.0.2 on 2018-06-12 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_squashed_0002_auto_20180612_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='dev',
        ),
    ]
