# Generated by Django 2.0.2 on 2018-06-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_state_dev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssrule',
            name='actioncap',
        ),
        migrations.RemoveField(
            model_name='ssrule',
            name='actiondev',
        ),
        migrations.RemoveField(
            model_name='ssrule',
            name='trigger1',
        ),
        migrations.RemoveField(
            model_name='ssrule',
            name='trigger2',
        ),
        migrations.AddField(
            model_name='ssrule',
            name='triggers',
            field=models.ManyToManyField(to='backend.State'),
        ),
    ]
