# Generated by Django 2.0.2 on 2018-06-13 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20180612_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poststate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EventEnd', to='backend.State')),
                ('prestate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EventStart', to='backend.State')),
            ],
        ),
        migrations.RemoveField(
            model_name='esrule',
            name='actioncap',
        ),
        migrations.RemoveField(
            model_name='esrule',
            name='actiondev',
        ),
        migrations.RemoveField(
            model_name='esrule',
            name='triggercapE',
        ),
        migrations.RemoveField(
            model_name='esrule',
            name='triggercapS',
        ),
        migrations.RemoveField(
            model_name='esrule',
            name='triggerdevE',
        ),
        migrations.RemoveField(
            model_name='esrule',
            name='triggerdevS',
        ),
        migrations.AlterField(
            model_name='ssrule',
            name='actionstate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SSactionstate', to='backend.State'),
        ),
        migrations.DeleteModel(
            name='ESRule',
        ),
    ]
