# Generated by Django 2.0.2 on 2018-06-13 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20180613_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='EERule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window', models.IntegerField()),
                ('actionstate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EEactionstate', to='backend.State')),
                ('triggers', models.ManyToManyField(to='backend.Event')),
            ],
        ),
        migrations.CreateModel(
            name='ESRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionstate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ESactionstate', to='backend.State')),
                ('triggerE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Event')),
                ('triggersS', models.ManyToManyField(to='backend.State')),
            ],
        ),
    ]
