# Generated by Django 2.0.2 on 2018-06-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20180614_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='active',
            field=models.NullBooleanField(),
        ),
    ]
