# Generated by Django 2.0.2 on 2018-06-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20180614_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='label',
            field=models.TextField(default='Foo is Bar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='label',
            field=models.TextField(default='Foo is Bar'),
            preserve_default=False,
        ),
    ]
