# Generated by Django 2.0.2 on 2018-06-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20180616_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='label',
        ),
        migrations.AddField(
            model_name='capability',
            name='label',
            field=models.TextField(default='Foo is $$STATE$$'),
            preserve_default=False,
        ),
    ]
