# Generated by Django 2.0.2 on 2018-06-18 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20180616_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capability',
            name='label',
        ),
        migrations.AddField(
            model_name='capability',
            name='commandlabel',
            field=models.TextField(default="Set $$DEVICE$$'s <django.db.models.fields.CharField> to $$STATE$$", null=True),
        ),
        migrations.AddField(
            model_name='capability',
            name='e_endlabel',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='capability',
            name='e_startlabel',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='capability',
            name='statelabel',
            field=models.TextField(default="$$DEVICE$$'s <django.db.models.fields.CharField> is $$STATE$$"),
        ),
        migrations.AddField(
            model_name='state',
            name='bool_endevent',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='bool_startevent',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='capability',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.Channel'),
        ),
        migrations.AlterField(
            model_name='state',
            name='dev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Device'),
        ),
    ]
