# Generated by Django 2.0.2 on 2018-06-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20180618_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='bool_endevent',
        ),
        migrations.RemoveField(
            model_name='state',
            name='bool_startevent',
        ),
        migrations.AddField(
            model_name='state',
            name='bi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='eend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='estart',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='capability',
            name='e_endlabel',
            field=models.TextField(default="$$DEVICE$$'s <django.db.models.fields.CharField> is changed from $$STATE$$", null=True),
        ),
        migrations.AlterField(
            model_name='capability',
            name='e_startlabel',
            field=models.TextField(default="$$DEVICE$$'s <django.db.models.fields.CharField> is changed to $$STATE$$", null=True),
        ),
    ]
