# Generated by Django 2.0.2 on 2018-06-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20180618_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capability',
            name='commandlabel',
            field=models.TextField(default="Set $$DEVICE$$'s $$CAPNAME$$ to $$STATE$$", null=True),
        ),
        migrations.AlterField(
            model_name='capability',
            name='e_endlabel',
            field=models.TextField(default="$$DEVICE$$'s $$CAPNAME$$ is changed from $$STATE$$", null=True),
        ),
        migrations.AlterField(
            model_name='capability',
            name='e_startlabel',
            field=models.TextField(default="$$DEVICE$$'s $$CAPNAME$$ is changed to $$STATE$$", null=True),
        ),
        migrations.AlterField(
            model_name='capability',
            name='statelabel',
            field=models.TextField(default="$$DEVICE$$'s $$CAPNAME$$ is $$STATE$$"),
        ),
    ]
