# Generated by Django 2.0.2 on 2018-06-21 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20180618_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esrule',
            name='triggerE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EStriggerE', to='backend.State'),
        ),
    ]
