# Generated by Django 2.0.2 on 2018-06-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20180621_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eerule',
            name='triggers',
            field=models.ManyToManyField(to='backend.State'),
        ),
    ]
