# Generated by Django 2.0.2 on 2018-07-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20180703_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='value',
            field=models.TextField(null=True),
        ),
    ]
