# Generated by Django 2.0.2 on 2018-07-08 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20180706_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='capability',
            name='changeable',
        ),
        migrations.RemoveField(
            model_name='state',
            name='eend',
        ),
        migrations.RemoveField(
            model_name='state',
            name='estart',
        ),
        migrations.RemoveField(
            model_name='state',
            name='valopts',
        ),
        migrations.RemoveField(
            model_name='state',
            name='valtype',
        ),
        migrations.AddField(
            model_name='capability',
            name='range_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='capability',
            name='range_min',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='capability',
            name='readable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='capability',
            name='type',
            field=models.TextField(choices=[('set', 'Set'), ('range', 'Range')], default='set'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capability',
            name='writeable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stateval',
            name='cap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Capability'),
        ),
    ]
