# Generated by Django 2.0.2 on 2018-07-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20180709_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setcapopt',
            name='cap',
        ),
        migrations.DeleteModel(
            name='SetCapOpt',
        ),
    ]
