# Generated by Django 2.0.2 on 2018-07-10 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20180710_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField(choices=[('set', 'Set'), ('range', 'Range'), ('bin', 'Binary')])),
            ],
        ),
        migrations.CreateModel(
            name='SetParamOpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bincap',
            name='capability_ptr',
        ),
        migrations.RemoveField(
            model_name='rangecap',
            name='capability_ptr',
        ),
        migrations.RemoveField(
            model_name='setcap',
            name='capability_ptr',
        ),
        migrations.RemoveField(
            model_name='capability',
            name='type',
        ),
        migrations.AlterField(
            model_name='capability',
            name='commandlabel',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='capability',
            name='e_endlabel',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='capability',
            name='e_startlabel',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='capability',
            name='statelabel',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='BinParam',
            fields=[
                ('parameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Parameter')),
                ('tval', models.TextField()),
                ('fval', models.TextField()),
            ],
            bases=('backend.parameter',),
        ),
        migrations.CreateModel(
            name='RangeParam',
            fields=[
                ('parameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Parameter')),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('interval', models.IntegerField(default=1)),
            ],
            bases=('backend.parameter',),
        ),
        migrations.CreateModel(
            name='SetParam',
            fields=[
                ('parameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Parameter')),
                ('numopts', models.IntegerField(default=0)),
            ],
            bases=('backend.parameter',),
        ),
        migrations.DeleteModel(
            name='BinCap',
        ),
        migrations.DeleteModel(
            name='RangeCap',
        ),
        migrations.DeleteModel(
            name='SetCap',
        ),
        migrations.AddField(
            model_name='parameter',
            name='cap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Capability'),
        ),
        migrations.AddField(
            model_name='setparamopt',
            name='param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SetParam'),
        ),
    ]
