# Generated by Django 2.0.2 on 2018-07-11 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20180710_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputParam',
            fields=[
                ('parameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Parameter')),
                ('inputtype', models.TextField(choices=[('int', 'Integer'), ('stxt', 'Short Text'), ('ltxt', 'Long Text')])),
            ],
            bases=('backend.parameter',),
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('state_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.State')),
                ('comp', models.TextField(choices=[('eq', 'is'), ('neq', 'is not'), ('lt', 'is less than'), ('lte', 'is at most'), ('gt', 'is greater than'), ('gte', 'is at least')])),
            ],
            bases=('backend.state',),
        ),
        migrations.AlterField(
            model_name='esrule',
            name='Etrigger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EStriggerE', to='backend.Trigger'),
        ),
        migrations.AlterField(
            model_name='esrule',
            name='Striggers',
            field=models.ManyToManyField(to='backend.Trigger'),
        ),
        migrations.AlterField(
            model_name='ssrule',
            name='triggers',
            field=models.ManyToManyField(to='backend.Trigger'),
        ),
    ]
