# Generated by Django 2.0.2 on 2018-07-12 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20180711_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='state_ptr',
        ),
        migrations.RemoveField(
            model_name='state',
            name='param',
        ),
        migrations.RemoveField(
            model_name='state',
            name='value',
        ),
        migrations.AddField(
            model_name='state',
            name='action',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='esrule',
            name='Etrigger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EStriggerE', to='backend.State'),
        ),
        migrations.AlterField(
            model_name='esrule',
            name='Striggers',
            field=models.ManyToManyField(to='backend.State'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='type',
            field=models.TextField(choices=[('set', 'Set'), ('range', 'Range'), ('bin', 'Binary'), ('input', 'Input')]),
        ),
        migrations.AlterField(
            model_name='ssrule',
            name='triggers',
            field=models.ManyToManyField(to='backend.State'),
        ),
        migrations.DeleteModel(
            name='Trigger',
        ),
        migrations.AddField(
            model_name='parval',
            name='par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Parameter'),
        ),
        migrations.AddField(
            model_name='parval',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.State'),
        ),
    ]
