# Generated by Django 2.0.2 on 2018-07-12 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20180712_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.TextField()),
                ('comp', models.TextField(choices=[('eq', 'is'), ('neq', 'is not'), ('lt', 'is less than'), ('lte', 'is at most'), ('gt', 'is greater than'), ('gte', 'is at least')])),
                ('par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Parameter')),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Capability')),
                ('dev2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Device')),
            ],
        ),
        migrations.AlterField(
            model_name='esrule',
            name='Etrigger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EStriggerE', to='backend.Trigger'),
        ),
        migrations.AlterField(
            model_name='esrule',
            name='Striggers',
            field=models.ManyToManyField(to='backend.Trigger'),
        ),
        migrations.AlterField(
            model_name='ssrule',
            name='triggers',
            field=models.ManyToManyField(to='backend.Trigger'),
        ),
        migrations.AddField(
            model_name='condition',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Trigger'),
        ),
    ]
