# Generated by Django 2.0.2 on 2018-07-16 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_auto_20180712_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trigger',
            old_name='cap2',
            new_name='cap',
        ),
        migrations.RenameField(
            model_name='trigger',
            old_name='dev2',
            new_name='dev',
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esrule',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ssrule',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='esrule',
            name='Etrigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EStriggerE', to='backend.Trigger'),
        ),
        migrations.AlterField(
            model_name='esrule',
            name='action',
            field=models.ForeignKey(limit_choices_to={'action': True}, on_delete=django.db.models.deletion.CASCADE, related_name='ESactionstate', to='backend.State'),
        ),
        migrations.AlterField(
            model_name='ssrule',
            name='action',
            field=models.ForeignKey(limit_choices_to={'action': True}, on_delete=django.db.models.deletion.CASCADE, related_name='SSactionstate', to='backend.State'),
        ),
    ]
