# Generated by Django 2.0.2 on 2018-07-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_channel_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangeparam',
            name='interval',
            field=models.FloatField(default=1.0),
        ),
    ]
