# Generated by Django 2.0.2 on 2018-07-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_auto_20180718_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capability',
            name='commandlabel',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='capability',
            name='eventlabel',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='capability',
            name='statelabel',
            field=models.TextField(max_length=256, null=True),
        ),
    ]
