# Generated by Django 2.0.2 on 2018-07-23 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_auto_20180719_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorParam',
            fields=[
                ('parameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Parameter')),
                ('mode', models.TextField(choices=[('rgb', 'RGB'), ('hsv', 'HSV'), ('hex', 'Hex')])),
            ],
            bases=('backend.parameter',),
        ),
        migrations.CreateModel(
            name='TimeParam',
            fields=[
                ('parameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Parameter')),
                ('mode', models.TextField(choices=[('24', '24-hour'), ('12', '12-hour')])),
            ],
            bases=('backend.parameter',),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='type',
            field=models.TextField(choices=[('set', 'Set'), ('range', 'Range'), ('bin', 'Binary'), ('color', 'Color'), ('time', 'Time'), ('input', 'Input')]),
        ),
    ]
