# Generated by Django 2.0.2 on 2018-07-24 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_auto_20180723_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaParam',
            fields=[
                ('parameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Parameter')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Trigger')),
            ],
            bases=('backend.parameter',),
        ),
    ]
