# Generated by Django 2.0.2 on 2018-07-25 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_auto_20180724_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('es', 'es'), ('ss', 'ss')], max_length=3)),
                ('when', models.TextField(choices=[('A', 'Always'), ('N', 'Never')])),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='mode',
            field=models.CharField(choices=[('rule', 'Rule'), ('sp', 'Safety Property')], default='rule', max_length=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ESSP',
            fields=[
                ('safetyprop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.SafetyProp')),
                ('conds', models.ManyToManyField(related_name='essp_conds', to='backend.Trigger')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essp_event', to='backend.Trigger')),
            ],
            bases=('backend.safetyprop',),
        ),
        migrations.CreateModel(
            name='SSSP',
            fields=[
                ('safetyprop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.SafetyProp')),
                ('conds', models.ManyToManyField(related_name='sssp_conds', to='backend.Trigger')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sssp_state', to='backend.Trigger')),
            ],
            bases=('backend.safetyprop',),
        ),
        migrations.AddField(
            model_name='safetyprop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
    ]
