# Generated by Django 2.0.2 on 2018-07-27 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_auto_20180725_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurationParam',
            fields=[
                ('parameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Parameter')),
                ('maxhours', models.IntegerField(default=23, null=True)),
                ('maxmins', models.IntegerField(default=59, null=True)),
                ('maxsecs', models.IntegerField(default=59, null=True)),
            ],
            bases=('backend.parameter',),
        ),
        migrations.RemoveField(
            model_name='metaparam',
            name='trigger',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='text',
        ),
        migrations.AddField(
            model_name='metaparam',
            name='is_event',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='text',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='trigger',
            name='chan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Channel'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='pos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trigger',
            name='text',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='inputparam',
            name='inputtype',
            field=models.TextField(choices=[('int', 'Integer'), ('stxt', 'Short Text'), ('ltxt', 'Long Text'), ('trig', 'Trigger')]),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='type',
            field=models.TextField(choices=[('set', 'Set'), ('range', 'Range'), ('bin', 'Binary'), ('color', 'Color'), ('time', 'Time'), ('duration', 'Duration'), ('input', 'Input'), ('meta', 'Meta')]),
        ),
    ]
