# Generated by Django 2.0.2 on 2018-07-27 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_durationparam_comp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP1',
            fields=[
                ('safetyprop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.SafetyProp')),
                ('triggers', models.ManyToManyField(to='backend.Trigger')),
            ],
            bases=('backend.safetyprop',),
        ),
        migrations.CreateModel(
            name='SP2',
            fields=[
                ('safetyprop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.SafetyProp')),
                ('comp', models.TextField(choices=[('eq', '='), ('neq', '!='), ('gt', '>'), ('lt', '<')], null=True)),
                ('time', models.IntegerField(null=True)),
                ('conds', models.ManyToManyField(related_name='sp2_conds', to='backend.Trigger')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sp2_state', to='backend.Trigger')),
            ],
            bases=('backend.safetyprop',),
        ),
        migrations.CreateModel(
            name='SP3',
            fields=[
                ('safetyprop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.SafetyProp')),
                ('comp', models.TextField(choices=[('eq', '='), ('neq', '!='), ('gt', '>'), ('lt', '<')], null=True)),
                ('occurrences', models.IntegerField(null=True)),
                ('time', models.IntegerField(null=True)),
                ('conds', models.ManyToManyField(related_name='sp3_conds', to='backend.Trigger')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sp3_event', to='backend.Trigger')),
            ],
            bases=('backend.safetyprop',),
        ),
        migrations.RemoveField(
            model_name='essp',
            name='conds',
        ),
        migrations.RemoveField(
            model_name='essp',
            name='event',
        ),
        migrations.RemoveField(
            model_name='essp',
            name='safetyprop_ptr',
        ),
        migrations.RemoveField(
            model_name='sssp',
            name='conds',
        ),
        migrations.RemoveField(
            model_name='sssp',
            name='safetyprop_ptr',
        ),
        migrations.RemoveField(
            model_name='sssp',
            name='state',
        ),
        migrations.RemoveField(
            model_name='safetyprop',
            name='code',
        ),
        migrations.AlterField(
            model_name='safetyprop',
            name='type',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')]),
        ),
        migrations.DeleteModel(
            name='ESSP',
        ),
        migrations.DeleteModel(
            name='SSSP',
        ),
    ]
