# Generated by Django 2.0.2 on 2018-07-28 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_auto_20180727_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='chan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Channel'),
        ),
    ]
