# Generated by Django 2.0.2 on 2018-07-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_state_chan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetyprop',
            name='when',
        ),
        migrations.AddField(
            model_name='device',
            name='public',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='safetyprop',
            name='always',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
