# Generated by Django 2.0.2 on 2018-07-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_auto_20180730_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='task',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='safetyprop',
            name='task',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
