# Generated by Django 2.0.2 on 2018-07-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_auto_20180730_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
