# Generated by Django 2.0.2 on 2018-08-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_device_chans'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='task',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
