# Generated by Django 2.0.2 on 2018-08-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0048_auto_20180806_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='icon',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
