# Generated by Django 2.0.2 on 2018-08-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_auto_20180807_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='comp',
            field=models.TextField(choices=[('=', 'is'), ('!=', 'is not'), ('<', 'is less than'), ('>', 'is greater than')]),
        ),
        migrations.AlterField(
            model_name='sp2',
            name='comp',
            field=models.TextField(choices=[('=', '='), ('!=', '!='), ('>', '>'), ('<', '<')], null=True),
        ),
        migrations.AlterField(
            model_name='sp3',
            name='comp',
            field=models.TextField(choices=[('=', '='), ('!=', '!='), ('>', '>'), ('<', '<')], null=True),
        ),
    ]
