# Generated by Django 2.0.2 on 2018-08-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_auto_20180807_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp3',
            name='timecomp',
            field=models.TextField(choices=[('=', '='), ('!=', '!='), ('>', '>'), ('<', '<')], null=True),
        ),
    ]
