# Generated by Django 2.0.2 on 2018-08-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_sp3_timecomp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='lastedit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='safetyprop',
            name='lastedit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
