# Generated by Django 2.0.2 on 2018-08-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_auto_20180809_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.TextField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='mode',
            field=models.CharField(choices=[('rules', 'Rule'), ('sp', 'Safety Property')], max_length=5),
        ),
    ]
