FROM ubuntu:xenial

USER root

RUN apt update && apt install -y wget net-tools g++ make python3-dev
RUN groupadd -g 1000 -r iftttuser && useradd --no-log-init -r -u 1000 -g iftttuser iftttuser && mkhomedir_helper iftttuser

# install spot model checker
RUN cd /root && \
    wget https://www.lrde.epita.fr/dload/spot/spot-2.7.5.tar.gz && \
    tar -zxvf spot-2.7.5.tar.gz && \
    cd /root/spot-2.7.5 && \
    ./configure && \
    make && make install && ldconfig && \
    cp -rf /usr/local/lib/python3.5/site-packages/* /usr/local/lib/python3.5/dist-packages

# install qm package
RUN cd /root && \
    wget http://robertdick.org/python/qm-0.2.tar.gz && \
    tar -zxvf qm-0.2.tar.gz &&\
    cd /root/qm-0.2 && \
    python3 setup.py install

# install AutoTap
ADD ./iot-autotap /root/AutoTap
RUN apt update && apt install -y python3-pip
RUN cd /root/AutoTap && \
    pip3 install .

# install django
ADD ./iot-tap-backend/requirements.txt /home/iftttuser
RUN pip3 install -r /home/iftttuser/requirements.txt
RUN apt update && apt install -y postgresql-client-9.5

USER iftttuser

WORKDIR /home/iftttuser/backend
CMD ["./initialize.sh"]
