# Generated by Django 2.0.2 on 2018-06-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=40)),
                ('device_name', models.CharField(max_length=80)),
                ('device_label', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='STApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_installed_app_id', models.CharField(max_length=40)),
                ('refresh_token', models.CharField(max_length=40)),
            ],
        ),
    ]
